# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CMake@1
  inputs:
    cmakeArgs: -DWITH_DLT_UNIT_TESTS=ON ..
- task: CMake@1
  inputs:
    cmakeArgs: --build .   
- task: CmdLine@2
  inputs:
    script: $(Build.Repository.LocalPath)/build/tests/gtest_dlt_daemon_common --gtest_output=xml:$(Build.Repository.LocalPath)/build/bin/test.xml
-  task: CmdLine@2
  inputs:
    script: $(Build.Repository.LocalPath)/build/tests/gtest_dlt_common --gtest_output=xml:$(Build.Repository.LocalPath)/build/bin/test2.xml
-  task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test*.xml'
    testRunTitle: 'My example test results'